name: Tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application image
        run: docker compose build app

      - name: Run PHPUnit
        run: docker compose run app vendor/bin/phpunit tests